sudo: required
services:
  - docker


before_install:
  - cd frontend
  - docker build -t pohltho/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pohltho/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-530798195059"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
