sudo: required
services:
  - docker


before_install:
  - cd frontend
  - docker build -t pohltho/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pohltho/docker-react npm run test
